package skill

import (
	"fmt"
	"reflect"
	"strings"
)

// Output describes one command's `--format json` payload. Payload is a
// zero value of the payload's Go type: only its type is used, so the
// documented schema is read from the same struct the command writes
// and cannot drift from it.
type Output struct {
	Command     string // e.g. "scan --format json"
	Description string
	Payload     any
}

// ExitCode is one row of the exit-code table.
type ExitCode struct {
	Code    int
	Meaning string
}

func renderOutput(opts Options) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Output schemas and exit codes\n\n")
	fmt.Fprintf(&b, "Generated by appstorys-cli %s from the Go types its commands write.\n\n", opts.CLIVersion)

	b.WriteString("## Envelope\n\n")
	b.WriteString("Every `--format json` command writes one JSON object:\n\n")
	b.WriteString("```json\n{ \"schemaVersion\": 1, \"data\": ... }\n```\n\n")
	b.WriteString("`schemaVersion` is bumped when a field is removed or its meaning changes. Field names are exactly as listed below (Go field names, capitalized). A top-level empty result is `[]`. Inside an object, a list or map that is empty may be `null`: treat `null` as empty. Property values and init arguments are never included, only property names and inferred types.\n\n")

	b.WriteString("## Commands\n\n")
	var order []reflect.Type
	seen := map[reflect.Type]bool{}
	for _, o := range opts.Outputs {
		t := reflect.TypeOf(o.Payload)
		if t == nil {
			return nil, fmt.Errorf("skill: output %q has a nil payload", o.Command)
		}
		fmt.Fprintf(&b, "### `appstorys-cli %s`\n\n%s\n\n`data` is %s.\n\n", o.Command, o.Description, payloadDescription(t))
		collectStructs(t, seen, &order)
	}

	b.WriteString("## Types\n\n")
	for _, t := range order {
		fmt.Fprintf(&b, "### `%s`\n\n| Field | Type | Meaning |\n| --- | --- | --- |\n", t.Name())
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			name, ok := jsonName(f)
			if !ok {
				continue
			}
			note := opts.FieldNotes[t.Name()+"."+f.Name]
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", name, typeString(f.Type), note)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Exit codes\n\n| Code | Meaning |\n| --- | --- |\n")
	for _, e := range opts.ExitCodes {
		fmt.Fprintf(&b, "| %d | %s |\n", e.Code, e.Meaning)
	}
	b.WriteString("\nOn any non-zero exit except 1, an `error: ...` line is written to standard error; read it before deciding what to do.\n")
	return []byte(b.String()), nil
}

func payloadDescription(t reflect.Type) string {
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	switch t.Kind() {
	case reflect.Slice, reflect.Array:
		return "a list of " + typeString(t.Elem())
	case reflect.Struct:
		return "one `" + t.Name() + "` object"
	default:
		return typeString(t)
	}
}

func typeString(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Ptr:
		return typeString(t.Elem()) + " or null"
	case reflect.Struct:
		return "`" + t.Name() + "`"
	case reflect.Slice, reflect.Array:
		return "list of " + typeString(t.Elem())
	case reflect.Map:
		return "map of " + typeString(t.Key()) + " to " + typeString(t.Elem())
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	default:
		return "any"
	}
}

// collectStructs records every struct type reachable from t, in the
// order first encountered.
func collectStructs(t reflect.Type, seen map[reflect.Type]bool, order *[]reflect.Type) {
	switch t.Kind() {
	case reflect.Ptr, reflect.Slice, reflect.Array:
		collectStructs(t.Elem(), seen, order)
	case reflect.Map:
		collectStructs(t.Elem(), seen, order)
	case reflect.Struct:
		if seen[t] {
			return
		}
		seen[t] = true
		*order = append(*order, t)
		for i := 0; i < t.NumField(); i++ {
			if _, ok := jsonName(t.Field(i)); ok {
				collectStructs(t.Field(i).Type, seen, order)
			}
		}
	}
}

// jsonName returns the field's JSON key, honoring a `json` tag, and
// false for fields encoding/json skips.
func jsonName(f reflect.StructField) (string, bool) {
	if !f.IsExported() {
		return "", false
	}
	tag := f.Tag.Get("json")
	if tag == "-" {
		return "", false
	}
	if name, _, _ := strings.Cut(tag, ","); name != "" {
		return name, true
	}
	return f.Name, true
}
