// Package skill renders the agent skill: a SKILL.md workflow plus
// per-platform reference files, all produced by the binary itself so
// the skill can never describe a different CLI or SDK version than the
// one that exported it.
//
// The parts that are facts about the SDK (symbols, reserved event
// names, supported versions) are generated from the same embedded
// symbol maps the scanner matches against; the parts that are facts
// about the JSON output are generated by reflecting over the Go types
// the commands actually write. Only the workflow prose and the
// per-platform "where things go / what stays manual" notes are static,
// and internal/cli's tests check every command and flag they mention
// against the real command tree.
package skill

import (
	"bytes"
	"embed"
	"fmt"
	"strings"
	"text/template"

	"github.com/appversal/appstorys-cli/internal/symbols"
)

//go:embed content/*
var content embed.FS

// Name is the skill's folder and frontmatter name.
const Name = "appstorys-integration"

// platformOrder is the spec's priority order, also the order the
// reference files are listed in.
var platformOrder = []struct{ Key, Title string }{
	{"android", "Android (Kotlin, Compose and XML)"},
	{"flutter", "Flutter (Dart)"},
	{"react-native", "React Native (TypeScript)"},
	{"ios", "iOS (Swift)"},
}

// File is one file of the exported skill; Path is relative to the
// directory the skill folder is exported into (so it starts with Name).
type File struct {
	Path    string
	Content []byte
}

// Options is everything Render needs from the running CLI.
type Options struct {
	CLIVersion string
	Symbols    map[string]*symbols.Map
	// Outputs, FieldNotes and ExitCodes feed reference/output.md; they
	// come from internal/cli because that package owns the types the
	// commands write.
	Outputs    []Output
	FieldNotes map[string]string
	ExitCodes  []ExitCode
}

// Render produces every file of the skill.
func Render(opts Options) ([]File, error) {
	type sdkVersion struct{ Platform, Version string }
	var versions []sdkVersion
	for _, p := range platformOrder {
		m, ok := opts.Symbols[p.Key]
		if !ok {
			return nil, fmt.Errorf("skill: no symbol map for platform %q", p.Key)
		}
		versions = append(versions, sdkVersion{p.Key, m.SDKVersion})
	}

	raw, err := content.ReadFile("content/SKILL.md.tmpl")
	if err != nil {
		return nil, err
	}
	tmpl, err := template.New("SKILL.md").Parse(string(raw))
	if err != nil {
		return nil, fmt.Errorf("skill: parsing SKILL.md template: %w", err)
	}
	var skillMD bytes.Buffer
	if err := tmpl.Execute(&skillMD, map[string]any{
		"CLIVersion":  opts.CLIVersion,
		"SDKVersions": versions,
	}); err != nil {
		return nil, fmt.Errorf("skill: rendering SKILL.md: %w", err)
	}

	files := []File{{Path: Name + "/SKILL.md", Content: skillMD.Bytes()}}

	for _, p := range platformOrder {
		ref, err := renderPlatform(p.Key, p.Title, opts.Symbols[p.Key], opts.CLIVersion)
		if err != nil {
			return nil, err
		}
		files = append(files, File{Path: Name + "/reference/" + p.Key + ".md", Content: ref})
	}

	out, err := renderOutput(opts)
	if err != nil {
		return nil, err
	}
	files = append(files, File{Path: Name + "/reference/output.md", Content: out})
	return files, nil
}

func renderPlatform(key, title string, m *symbols.Map, cliVersion string) ([]byte, error) {
	notes, err := content.ReadFile("content/platform_" + key + ".md")
	if err != nil {
		return nil, fmt.Errorf("skill: no notes for platform %q: %w", key, err)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s reference\n\n", title)
	fmt.Fprintf(&b, "Generated by appstorys-cli %s. The SDK facts below come from the symbol map embedded in that binary, the same one its scanner matches against.\n\n", cliVersion)
	fmt.Fprintf(&b, "- Supported SDK version: %s\n", m.SDKVersion)
	if m.Import != "" {
		fmt.Fprintf(&b, "- Import: `%s`\n", m.Import)
	}
	if len(m.Receivers) > 0 {
		fmt.Fprintf(&b, "- Calls are matched on the receiver%s %s. Add aliases under `receivers` in `.appstorys-cli.yaml` if the app wraps the SDK singleton.\n",
			plural(len(m.Receivers)), codeList(m.Receivers))
	}
	b.WriteString("\n")

	b.WriteString("## Symbols the CLI recognizes\n\n")
	if len(m.Symbols) == 0 {
		b.WriteString("The CLI has no symbol map for this platform yet.\n\n")
	} else {
		writeSymbolTable(&b, m)
	}

	b.WriteString("## Reserved event names\n\n")
	if len(m.ReservedEvents) == 0 {
		b.WriteString("None recorded for this platform.\n\n")
	} else {
		fmt.Fprintf(&b, "These are the SDK's own system events. A custom event must not use them: %s. `lint` reports it as an error.\n\n", codeList(m.ReservedEvents))
	}

	b.WriteString("## Metadata keys the SDK overwrites\n\n")
	if len(m.MergedMetadataKeys) == 0 {
		b.WriteString("No complete list is recorded for this platform. The SDK overwrites some device-info keys (for example `model`, `platform`, `app_version` and `locale`), so do not use those as event metadata keys.\n\n")
	} else {
		fmt.Fprintf(&b, "The SDK overwrites these with device info, so a custom metadata key with the same name is lost: %s. `lint` warns about it.\n\n", codeList(m.MergedMetadataKeys))
	}

	b.Write(notes)
	if !strings.HasSuffix(b.String(), "\n") {
		b.WriteString("\n")
	}
	return []byte(b.String()), nil
}

func writeSymbolTable(b *strings.Builder, m *symbols.Map) {
	type row struct{ concept, symbol, name, props, positions, position, note string }
	rows := make([]row, 0, len(m.Symbols))
	var hasName, hasProps, hasPositions, hasPosition, hasNote bool
	for _, s := range m.Symbols {
		symbol := s.Call
		if symbol == "" {
			symbol = s.Constructor + " (constructor)"
		}
		r := row{
			concept:   s.Concept,
			symbol:    "`" + symbol + "`",
			name:      argRef(s.NameArg),
			props:     argRef(s.PropsArg),
			positions: argRef(s.PositionsArg),
			position:  argRef(s.PositionArg),
		}
		if s.MustBeInside != "" {
			r.note = "must be inside `" + s.MustBeInside + "`"
		}
		hasName = hasName || r.name != ""
		hasProps = hasProps || r.props != ""
		hasPositions = hasPositions || r.positions != ""
		hasPosition = hasPosition || r.position != ""
		hasNote = hasNote || r.note != ""
		rows = append(rows, r)
	}

	headers := []string{"Concept", "Symbol"}
	if hasName {
		headers = append(headers, "Name argument")
	}
	if hasProps {
		headers = append(headers, "Properties argument")
	}
	if hasPositions {
		headers = append(headers, "Positions argument")
	}
	if hasPosition {
		headers = append(headers, "Position argument")
	}
	if hasNote {
		headers = append(headers, "Notes")
	}
	b.WriteString("| " + strings.Join(headers, " | ") + " |\n")
	b.WriteString("|" + strings.Repeat(" --- |", len(headers)) + "\n")
	for _, r := range rows {
		cells := []string{r.concept, r.symbol}
		if hasName {
			cells = append(cells, dash(r.name))
		}
		if hasProps {
			cells = append(cells, dash(r.props))
		}
		if hasPositions {
			cells = append(cells, dash(r.positions))
		}
		if hasPosition {
			cells = append(cells, dash(r.position))
		}
		if hasNote {
			cells = append(cells, dash(r.note))
		}
		b.WriteString("| " + strings.Join(cells, " | ") + " |\n")
	}
	b.WriteString("\n")
}

func argRef(a *symbols.ArgRef) string {
	if a == nil {
		return ""
	}
	var parts []string
	if a.Named != "" {
		parts = append(parts, "named `"+a.Named+"`")
	}
	if a.Positional != nil {
		parts = append(parts, fmt.Sprintf("positional %d", *a.Positional))
	}
	return strings.Join(parts, ", ")
}

func dash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}

func codeList(items []string) string {
	quoted := make([]string, len(items))
	for i, it := range items {
		quoted[i] = "`" + it + "`"
	}
	return strings.Join(quoted, ", ")
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}
