package cli

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/appversal/appstorys-cli/internal/catalog"
	"github.com/appversal/appstorys-cli/internal/extract"
	"github.com/appversal/appstorys-cli/internal/rules"
	"github.com/appversal/appstorys-cli/internal/skill"
	"github.com/appversal/appstorys-cli/internal/suggest"
	"github.com/appversal/appstorys-cli/internal/symbols"
)

func newSkillCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "skill",
		Short: "Export the agent skill that drives this CLI",
	}
	cmd.AddCommand(newSkillExportCmd())
	return cmd
}

func newSkillExportCmd() *cobra.Command {
	var (
		dir   string
		force bool
	)

	cmd := &cobra.Command{
		Use:   "export",
		Short: "Write the appstorys-integration skill matching this CLI version",
		Long: "Writes the appstorys-integration skill folder (SKILL.md plus reference files) " +
			"into --dir, by default <root>/.claude/skills. The skill is generated by this binary, so " +
			"it always describes this CLI and the SDK versions it supports. An existing file that " +
			"differs (for example from an older CLI version) is only replaced with --force.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			app := FromContext(cmd.Context())

			opts, err := skillOptions()
			if err != nil {
				return &CLIError{Code: ExitUsageOrConfig, Err: err}
			}
			files, err := skill.Render(opts)
			if err != nil {
				return &CLIError{Code: ExitUsageOrConfig, Err: err}
			}

			target := dir
			if target == "" {
				target = filepath.Join(app.Root, ".claude", "skills")
			}

			var toWrite []skill.File
			var differing []string
			for _, f := range files {
				existing, err := os.ReadFile(filepath.Join(target, f.Path))
				switch {
				case os.IsNotExist(err):
					toWrite = append(toWrite, f)
				case err != nil:
					return fmt.Errorf("reading %s: %w", filepath.Join(target, f.Path), err)
				case !bytes.Equal(existing, f.Content):
					toWrite = append(toWrite, f)
					differing = append(differing, f.Path)
				}
			}

			if len(toWrite) == 0 {
				fmt.Fprintf(app.Out, "%s is already up to date.\n", filepath.Join(target, skill.Name))
				return nil
			}
			if len(differing) > 0 && !force {
				return &CLIError{Code: ExitRefused, Err: fmt.Errorf(
					"%d existing file(s) under %s differ from this CLI version's skill (%v); re-run with --force to overwrite them",
					len(differing), filepath.Join(target, skill.Name), differing)}
			}

			for _, f := range toWrite {
				path := filepath.Join(target, f.Path)
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					return fmt.Errorf("creating %s: %w", filepath.Dir(path), err)
				}
				if err := os.WriteFile(path, f.Content, 0o644); err != nil {
					return fmt.Errorf("writing %s: %w", path, err)
				}
			}
			fmt.Fprintf(app.Out, "Wrote %d file(s) to %s.\n", len(toWrite), filepath.Join(target, skill.Name))
			return nil
		},
	}

	cmd.Flags().StringVar(&dir, "dir", "", "directory to write the skill folder into (default <root>/.claude/skills)")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite existing skill files that differ")
	return cmd
}

// skillOptions gathers everything the skill renderer needs from this
// binary: the embedded symbol maps, and the exact Go types the
// --format json commands write.
func skillOptions() (skill.Options, error) {
	maps, err := symbols.Load()
	if err != nil {
		return skill.Options{}, fmt.Errorf("loading SDK symbol maps: %w", err)
	}
	return skill.Options{
		CLIVersion: Version,
		Symbols:    maps,
		Outputs: []skill.Output{
			{
				Command:     "scan --format json",
				Description: "Every recognized SDK call site, sorted by file then line (`--group-by name` sorts by name). Narrow it with `--kind`, `--name` and `--platform`.",
				Payload:     []extract.CallSite{},
			},
			{
				Command:     "lint --format json",
				Description: "Lint findings, empty when clean. `validate --format json` writes the same payload and exits 1 when a finding reaches `--fail-on`.",
				Payload:     []rules.Finding{},
			},
			{
				Command:     "doctor --format json",
				Description: "One row per check: the init check first, then one per discovered screen. Exit code 1 when any row's `Status` starts with `fail:`.",
				Payload:     []DoctorResult{},
			},
			{
				Command:     "integrate --format json",
				Description: "The suggestions `integrate` would make, not deduplicated: an edit needing several insertions (such as an opening and closing tag) appears as several entries sharing one `ID`, and `--suggestion <id>` acts on all of them together.",
				Payload:     []suggest.Suggestion{},
			},
			{
				Command:     "events list --format json",
				Description: "The deduplicated catalog of events, screens and widget positions. Call sites whose name is not a literal are listed separately under `Dynamic`, since they cannot be registered.",
				Payload:     catalog.Catalog{},
			},
			{
				Command:     "events list --only events --format json",
				Description: "With `--only events`, `--only screens` or `--only positions`, just that list.",
				Payload:     []catalog.Item{},
			},
		},
		FieldNotes: map[string]string{
			"CallSite.Kind":       "`init`, `screen`, `event`, `overlay-host`, `placement` or `tag`",
			"CallSite.Name":       "The literal name; empty when `Dynamic` is true or the call has no name (init, overlay-host, placement)",
			"CallSite.Dynamic":    "True when the name is not a plain literal, so it cannot be registered",
			"CallSite.Properties": "Event property names mapped to an inferred type: `string`, `number`, `bool` or `dynamic`. Values are never included",
			"CallSite.File":       "Path relative to the project root, with forward slashes",
			"CallSite.Line":       "1-based",
			"CallSite.Col":        "1-based",
			"CallSite.Enclosing":  "Best-effort enclosing function or class, for example `LoginViewModel.submit`",
			"CallSite.Via":        "The SDK symbol that matched, as in the platform reference's symbol table",
			"CallSite.Position":   "Widget position(s), comma-joined when a screen call lists several",
			"CallSite.Platform":   "`android`, `flutter`, `react-native` or `ios`",

			"Finding.RuleID":   "For example `reserved-event-name`",
			"Finding.Severity": "`error`, `warning` or `info`",
			"Finding.Message":  "Human-readable explanation",
			"Finding.Site":     "The call site the finding is about; an empty object for a whole-project finding such as `init-missing`",
			"Finding.Fix":      "Always null in this version",

			"DoctorResult.Check":     "`init` or `screen`",
			"DoctorResult.Screen":    "The screen (widget, Activity or route) being checked; `-` for the init check",
			"DoctorResult.File":      "Relative path, or `-` when no file applies",
			"DoctorResult.Line":      "1-based; 0 when no line applies",
			"DoctorResult.TrackedAs": "The literal screen name, `<dynamic>`, or `-` when untracked",
			"DoctorResult.Overlay":   "`root` when an overlay host was found, `missing` when not, `-` for the init check",
			"DoctorResult.Status":    "`pass`, `fail: <reason>` or `warn: heuristic: <reason>`",

			"Suggestion.ID":         "Stable across runs on unchanged code",
			"Suggestion.Kind":       "`init`, `overlay-host`, `screen` or `placement`",
			"Suggestion.File":       "Relative path; may not exist yet, in which case the edit creates it",
			"Suggestion.Line":       "Not populated in this version",
			"Suggestion.Anchor":     "The route, class, function or widget the edit targets",
			"Suggestion.InsertAt":   "Byte offset into `File` where `Snippet` is inserted; ignored for a new file",
			"Suggestion.Snippet":    "The text inserted; for a new file, the whole file",
			"Suggestion.Confidence": "0 to 1",
			"Suggestion.Reason":     "Human-readable explanation",
			"Suggestion.Requires":   "Things to confirm or do by hand; `confirm screen name` means ask the developer to approve the proposed name",

			"Catalog.Events":    "Distinct literal event names",
			"Catalog.Screens":   "Distinct literal screen names",
			"Catalog.Positions": "Distinct widget positions, not linked to a screen in this version",
			"Catalog.Dynamic":   "Event and screen call sites whose name is not a literal",

			"Item.Kind":       "`event`, `screen` or `position`",
			"Item.Platforms":  "Platforms the item was found on",
			"Item.CallSites":  "How many call sites use it",
			"Item.Properties": "Property names to inferred types, as on `CallSite`",
		},
		ExitCodes: []skill.ExitCode{
			{Code: ExitOK, Meaning: "Success; no findings at or above the threshold"},
			{Code: ExitFindings, Meaning: "`lint`, `validate` or `doctor` found errors or failing checks (their output has the details)"},
			{Code: ExitUsageOrConfig, Meaning: "Usage or config error (bad flag, bad value, unreadable config)"},
			{Code: ExitProjectUnsupported, Meaning: "No project detected under `--root`, or its platform isn't supported by that command (iOS isn't supported yet)"},
			{Code: ExitRegistrationFailed, Meaning: "Registration failed; unused in this version, which has no `events register`"},
			{Code: ExitRefused, Meaning: "Refused to write: dirty git tree for `--apply`, or an existing file differs for `skill export` without `--force`"},
		},
	}, nil
}
